<?= $this->extend('layouts/admin') ?>
<?= $this->section('title') ?><?= esc(lang('App.trips_management')) ?><?= $this->endSection() ?>
<?= $this->section('content') ?>
<?php
$trips = $trips ?? [];
$ships = $ships ?? [];
$filters = $filters ?? ['q' => '', 'ship_id' => 0, 'status' => '', 'from_date' => '', 'to_date' => ''];
$stats = $stats ?? ['total_trips' => 0, 'filtered_trips' => 0, 'upcoming' => 0, 'active' => 0, 'completed' => 0];
$exportQuery = http_build_query(array_filter($filters, static fn ($value) => $value !== '' && $value !== 0));
$isAdmin = is_admin_user();
?>
<div class="page-card p-4 p-lg-5 mb-4 d-flex flex-column flex-lg-row justify-content-between align-items-lg-center gap-3">
    <div><div class="section-title"><?= esc(lang('App.nav_trips')) ?></div><h1 class="page-title h2 mb-2"><?= esc(lang('App.trips_management')) ?></h1><p class="muted mb-0"><?= esc(lang('App.trips_management_desc')) ?></p></div>
    <?php if ($isAdmin): ?><div class="d-flex gap-2 flex-wrap"><a href="<?= site_url('trips/export') . ($exportQuery ? '?' . $exportQuery : '') ?>" class="btn btn-outline-light px-4 py-2"><i class="fa-solid fa-file-csv me-2"></i><?= esc(lang('App.export_csv')) ?></a><a href="<?= site_url('trips/create') ?>" class="btn btn-primary px-4 py-2"><i class="fa-solid fa-plus me-2"></i><?= esc(lang('App.add_new_trip')) ?></a></div><?php endif; ?>
</div>
<div class="row g-3 mb-4">
<?php foreach ([
    [lang('App.total'), (int) $stats['total_trips'], 'fa-route'],
    [lang('App.filtered_results'), (int) $stats['filtered_trips'], 'fa-filter'],
    [lang('App.trip_status_upcoming'), (int) $stats['upcoming'], 'fa-calendar-day'],
    [lang('App.trip_status_active'), (int) $stats['active'], 'fa-water'],
    [lang('App.trip_status_completed'), (int) $stats['completed'], 'fa-circle-check'],
] as [$label, $value, $icon]): ?><div class="col-sm-6 col-xl"><div class="stat-card rounded-4 p-3 h-100 d-flex align-items-center gap-3"><span class="metric-icon"><i class="fa-solid <?= esc($icon) ?>"></i></span><div><div class="muted small mb-1"><?= esc($label) ?></div><div class="h4 mb-0"><?= number_format($value) ?></div></div></div></div><?php endforeach; ?>
</div>
<div class="form-shell p-3 p-md-4 mb-4"><form method="get" action="<?= site_url('trips') ?>" class="row g-3 align-items-end"><div class="col-md-4 col-xl-3"><label class="form-label" for="trip-q"><?= esc(lang('App.search')) ?></label><input id="trip-q" type="search" name="q" value="<?= esc($filters['q']) ?>" class="form-control" placeholder="<?= esc(lang('App.search_trips_placeholder')) ?>"></div><div class="col-md-4 col-xl-2"><label class="form-label" for="trip-ship"><?= esc(lang('App.ship')) ?></label><select id="trip-ship" name="ship_id" class="form-select"><option value="0"><?= esc(lang('App.all_ships')) ?></option><?php foreach ($ships as $ship): ?><option value="<?= (int) ($ship['id'] ?? 0) ?>" <?= (int) $filters['ship_id'] === (int) ($ship['id'] ?? 0) ? 'selected' : '' ?>><?= esc($ship['name'] ?? '') ?></option><?php endforeach; ?></select></div><div class="col-md-4 col-xl-2"><label class="form-label" for="trip-status"><?= esc(lang('App.trip_status')) ?></label><select id="trip-status" name="status" class="form-select"><option value=""><?= esc(lang('App.all_statuses')) ?></option><?php foreach (['upcoming', 'active', 'completed'] as $status): ?><option value="<?= $status ?>" <?= $filters['status'] === $status ? 'selected' : '' ?>><?= esc(lang('App.trip_status_' . $status)) ?></option><?php endforeach; ?></select></div><div class="col-md-5 col-xl-2"><label class="form-label" for="from-date"><?= esc(lang('App.from_date')) ?></label><input id="from-date" type="date" name="from_date" value="<?= esc($filters['from_date']) ?>" class="form-control"></div><div class="col-md-5 col-xl-2"><label class="form-label" for="to-date"><?= esc(lang('App.to_date')) ?></label><input id="to-date" type="date" name="to_date" value="<?= esc($filters['to_date']) ?>" class="form-control"></div><div class="col-md-2 col-xl-1 d-grid"><button type="submit" class="btn btn-primary"><i class="fa-solid fa-filter"></i><span class="visually-hidden"><?= esc(lang('App.apply')) ?></span></button></div></form></div>
<div class="table-shell p-3 p-md-4"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th><?= esc(lang('App.id')) ?></th><th><?= esc(lang('App.ship')) ?></th><th><?= esc(lang('App.route')) ?></th><th><?= esc(lang('App.departure_date')) ?></th><th><?= esc(lang('App.arrival_date')) ?></th><th><?= esc(lang('App.trip_status')) ?></th><th><?= esc(lang('App.duration_hours')) ?></th><th class="text-end"><?= esc(lang('App.actions')) ?></th></tr></thead><tbody>
<?php if ($trips === []): ?><tr><td colspan="8" class="text-center py-5"><i class="fa-regular fa-calendar-xmark fa-2x muted mb-3 d-block"></i><strong><?= esc(lang('App.no_results')) ?></strong></td></tr><?php else: foreach ($trips as $trip): ?><tr><td class="muted">#<?= (int) ($trip['id'] ?? 0) ?></td><td><strong><?= esc($trip['ship_name'] ?? '') ?></strong></td><td><span><?= esc($trip['departure_port_name'] ?? '') ?></span><i class="fa-solid fa-arrow-right-long mx-2 muted"></i><span><?= esc($trip['arrival_port_name'] ?? '') ?></span></td><td class="text-nowrap"><?= esc(format_datetime($trip['departure_date'] ?? null)) ?></td><td class="text-nowrap"><?= esc(format_datetime($trip['arrival_date'] ?? null)) ?></td><td><span class="badge rounded-pill text-bg-<?= esc($trip['status_class'] ?? 'secondary') ?>"><?= esc($trip['status_label'] ?? '') ?></span></td><td><?= esc((string) ($trip['duration_hours'] ?? 0)) ?></td><td class="text-end text-nowrap"><div class="d-inline-flex gap-2"><a href="<?= site_url('trips/show/' . (int) $trip['id']) ?>" class="btn btn-sm btn-outline-info" aria-label="<?= esc(lang('App.view')) ?>"><i class="fa-regular fa-eye"></i></a><?php if ($isAdmin && ($trip['status_class'] ?? '') === 'info'): ?><a href="<?= site_url('trips/edit/' . (int) $trip['id']) ?>" class="btn btn-sm btn-outline-warning" aria-label="<?= esc(lang('App.edit')) ?>"><i class="fa-regular fa-pen-to-square"></i></a><form method="post" action="<?= site_url('trips/delete/' . (int) $trip['id']) ?>" onsubmit="return confirm(<?= json_encode(lang('App.confirm_delete'), JSON_UNESCAPED_UNICODE) ?>)"><?= csrf_field() ?><button type="submit" class="btn btn-sm btn-outline-danger" aria-label="<?= esc(lang('App.delete')) ?>"><i class="fa-regular fa-trash-can"></i></button></form><?php elseif ($isAdmin): ?><button type="button" class="btn btn-sm btn-outline-secondary" disabled title="<?= esc(lang('App.trip_history_locked')) ?>" aria-label="<?= esc(lang('App.trip_history_locked')) ?>"><i class="fa-solid fa-lock"></i></button><?php endif; ?></div></td></tr><?php endforeach; endif; ?>
</tbody></table></div><?php if (isset($pager)): ?><div class="mt-4"><?= $pager->links() ?></div><?php endif; ?></div>
<?= $this->endSection() ?>
