<?= $this->extend('layouts/admin') ?>
<?= $this->section('title') ?><?= lang('App.messages_title') ?><?= $this->endSection() ?>
<?= $this->section('content') ?>
<?php $messages = $messages ?? []; $filters = $filters ?? ['status'=>'','q'=>'']; $stats = $stats ?? ['total'=>0,'unread'=>0]; ?>
<div class="page-card p-4 p-lg-5 mb-4"><div class="section-title"><?= esc(lang('App.nav_messages')) ?></div><h1 class="page-title h2 mb-2"><?= esc(lang('App.messages_title')) ?></h1><p class="muted mb-0"><?= esc(lang('App.messages_desc')) ?></p></div>
<div class="row g-3 mb-4"><div class="col-md-6"><div class="kpi-card"><span class="kpi-icon"><i class="fa-solid fa-envelope"></i></span><span><span class="muted small d-block"><?= esc(lang('App.total_messages')) ?></span><span class="kpi-value"><?= (int) $stats['total'] ?></span></span></div></div><div class="col-md-6"><div class="kpi-card"><span class="kpi-icon"><i class="fa-solid fa-envelope-open-text"></i></span><span><span class="muted small d-block"><?= esc(lang('App.unread_messages')) ?></span><span class="kpi-value"><?= (int) $stats['unread'] ?></span></span></div></div></div>
<div class="table-shell p-3 p-lg-4">
    <form method="get" class="row g-3 align-items-end mb-4"><div class="col-md-7"><label class="form-label"><?= esc(lang('App.search')) ?></label><input class="form-control" name="q" value="<?= esc($filters['q']) ?>" placeholder="<?= esc(lang('App.dashboard_global_search_placeholder')) ?>"></div><div class="col-md-3"><label class="form-label"><?= esc(lang('App.status')) ?></label><select class="form-select" name="status"><option value=""><?= esc(lang('App.all')) ?></option><option value="unread" <?= $filters['status']==='unread'?'selected':'' ?>><?= esc(lang('App.unread')) ?></option><option value="read" <?= $filters['status']==='read'?'selected':'' ?>><?= esc(lang('App.read')) ?></option></select></div><div class="col-md-2 d-flex gap-2"><button class="btn btn-primary flex-grow-1" type="submit"><?= esc(lang('App.filter')) ?></button><a class="btn btn-outline-light" href="<?= site_url('messages') ?>" aria-label="<?= esc(lang('App.reset')) ?>"><i class="fa-solid fa-rotate-left"></i></a></div></form>
    <div class="table-responsive"><table class="table table-hover"><thead><tr><th><?= esc(lang('App.sender')) ?></th><th><?= esc(lang('App.subject')) ?></th><th><?= esc(lang('App.status')) ?></th><th><?= esc(lang('App.date')) ?></th><th><?= esc(lang('App.actions')) ?></th></tr></thead><tbody>
    <?php if ($messages === []): ?><tr><td colspan="5" class="text-center muted py-5"><?= esc(lang('App.no_messages')) ?></td></tr>
    <?php else: foreach ($messages as $item): ?><tr class="<?= (int) ($item['is_read'] ?? 0) === 0 ? 'fw-bold' : '' ?>"><td><div><?= esc($item['name']) ?></div><small class="muted"><?= esc($item['email']) ?></small></td><td><?= esc($item['subject']) ?></td><td><span class="badge rounded-pill text-bg-<?= (int) $item['is_read'] === 1 ? 'secondary' : 'primary' ?>"><?= esc((int) $item['is_read'] === 1 ? lang('App.read') : lang('App.unread')) ?></span></td><td><?= esc(format_datetime($item['created_at'])) ?></td><td><a class="btn btn-sm btn-outline-light" href="<?= site_url('messages/' . (int) $item['id']) ?>" aria-label="<?= esc(lang('App.view')) ?>"><i class="fa-regular fa-eye"></i></a></td></tr><?php endforeach; endif; ?>
    </tbody></table></div><div class="mt-4"><?= $pager?->links() ?></div>
</div>
<?= $this->endSection() ?>
